name: temperature-attribution-2022
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - fair==2.1.3
  - h5py
  - jupyter
  - matplotlib
  - nbstripout
  - netcdf4
  - numpy
  - pandas
  - scipy
  - xarray
